[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1000

remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'oz/=lib/openzeppelin-contracts/contracts/',
    'lib-sc/=lib/lib-sc/src/'
]

# ignore solc warnings
# 1878 missing license
# 9302 unused low level return call
# 5667 unused function parameter
ignored_error_codes = [1878, 9302, 5667]

[rpc_endpoints]
mainnet = '${HTTP_URL_ETH}'
arbitrum = '${HTTP_URL_ARBITRUM}'
goerli = '${HTTP_URL_GOERLI}'
anvil = '${HTTP_URL_ANVIL}'
archive = '${HTTP_URL_ARCHIVE}'

[etherscan]
mainnet = {key = '${API_KEY_ETHERSCAN}'}
goerli = {key = '${API_KEY_ETHERSCAN}', url = 'https://api-goerli.etherscan.io/api'}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config